// <auto-generated />
using BuildingSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingSearch.Data.Migrations
{
    [DbContext(typeof(SearchContext))]
    [Migration("20240303091031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("BuildingSearch.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BATCH_NO")
                        .HasColumnType("TEXT");

                    b.Property<string>("CAD_ZONE")
                        .HasColumnType("TEXT");

                    b.Property<string>("DATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("DATE_RETURNED")
                        .HasColumnType("TEXT");

                    b.Property<string>("DEVELOPER_S_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("FILE_NUMBER")
                        .HasColumnType("TEXT");

                    b.Property<string>("ORIGINAL_FILE_LOCATION")
                        .HasColumnType("TEXT");

                    b.Property<string>("PLOT_NO")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
